import React from "react";

const ImageContainer = () => {
  return (
    <div className="trading-pic mb-[3%] flex sm:flex-nowrap flex-wrap justify-between sm:space-x-4 md:space-y-0 space-y-4">
      <div className="firstImageDiv w-full flex flex-col items-center">
        <div className="firstImage relative">
          <img
            src="/assets/backCard.png"
            alt="icon"
            className=""
            width={400}
            height={500}
          />
          <img
            src="/assets/grouplines.png"
            alt="icon"
            className="absolute inset-0 "
            width={400}
            height={500}
          />
          <img
            src="/assets/gradient.png"
            alt="icon"
            className="absolute inset-0 "
            width={400}
            height={500}
          />
          <img
            // src="https://image.rinxo.com/web_images/market_page/register_account.png"
            src="/assets/how-it-works-1.png"
            alt="icon"
            className="absolute inset-0 "
            width={400}
            height={500}
          />
        </div>
        <div className="headingDiv text-center mt-4 sm:hidden">
          <div className="text-[18px] md:text-[24px] text-[#0A0A14] font-semibold">Promote Your Partner Link</div>
          <div className="text-[#54545B] text-[14px]  md:text-[16px] font-normal mb-5">
            Use the tools and materials we provide to share your link with potential traders
          </div>
        </div>
      </div>
      <div className="secondImageDiv w-full flex flex-col items-center">
        <div className="secondImage relative">
          <img
            src="/assets/backCard.png"
            alt="icon"
            className=""
            width={400}
            height={500}
          />
          <img
            src="/assets/grouplines.png"
            alt="icon"
            className="absolute inset-0 "
            width={400}
            height={500}
          />
          <img
            src="/assets/gradient.png"
            alt="icon"
            className="absolute inset-0 "
            width={400}
            height={500}
          />
          <img
            // src="https://image.rinxo.com/web_images/market_page/Make_a_deposit.png"
            src="/assets/how-it-works-2.png"
            alt="icon"
            className="absolute inset-0 "
            width={400}
            height={400}
          />
        </div>
        <div className="headingDiv text-center mt-4 sm:hidden">
          <div className="text-[18px] md:text-[24px] text-[#0A0A14] font-semibold">
            Clients Register & Trade
          </div>
          <div className="text-[#54545B] text-[14px]  md:text-[16px] font-normal mb-5">
            Your referred clients sign up, deposit funds, and start trading
          </div>
        </div>
      </div>
      <div className="thirdImageDiv w-full flex flex-col items-center">
        <div className="thirdImage relative">
          <img
            src="/assets/backCard.png"
            alt="icon"
            className=""
            width={400}
            height={500}
          />
          <img
            src="/assets/grouplines.png"
            alt="icon"
            className="absolute inset-0 "
            width={400}
            height={500}
          />
          <img
            src="/assets/gradient.png"
            alt="icon"
            className="absolute inset-0 "
            width={400}
            height={500}
          />
          <img
            // src="https://image.rinxo.com/web_images/market_page/start_trading.png"
            src="/assets/how-it-works-3.png"
            alt="icon"
            className="absolute bottom-0 right-0 inset-0 "
            width={400}
            height={500}
          />
        </div>
        <div className="headingDiv text-center mt-4 sm:hidden">
          <div className="text-[18px] md:text-[24px] text-[#0A0A14] font-semibold">
            You Earn Commission
          </div>
          <div className="text-[#54545B] text-[14px]  md:text-[16px] font-normal">
          Receive a percentage of the revenue generated by each client's trading activity. 
          </div>
        </div>
      </div>
    </div>
  );
};

export default ImageContainer;
