import * as React from 'react'
import Banner from '../../components/Banner'
import WhyTradeSection from '../../components/WhyTradeSection'
import TradingRinxo from '../../components/TradingRinxo'
import TradingExperience from '../../components/TradingExperience'
import PaymentTicker from '../../components/PaymentTicker'
import StartEarning from '../../components/StartEarning'


const Home = () => {
  return (
    <>
      <Banner />
      <WhyTradeSection />
      <TradingRinxo
        title={'How it works'}
        desc={true}
        card_1desc={
          'Use the tools and materials we provide to share your link with potential traders'
        }
        card_2desc={
          'Your referred clients sign up, deposit funds, and start trading.'
        }
        card_3desc={
          "Receive a percentage of the revenue generated by each client's trading activity."
        }
        buttonLabel={'Get Started Today'}
      />
<TradingExperience />
      <PaymentTicker />
      <StartEarning />
    </>
  )
}

export default Home
